Q2-A mohasebe be ravesh bazgashti

In [1]:
import math
import numpy as np
A = np.array([[1, 1], [1, 0]])

def fibo_recursive(A, n):
    if(n == 1):
        return A
    P = fibo_recursive(A, math.floor(n / 2))
    if(n % 2 == 1):
        return np.matmul(np.matmul(P, P), A)
    else:
        return np.matmul(P, P)


Q2-B mohasebe be ravesh meghdar vizhe

In [2]:
def fibo_eig(A, n):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    digonal_matrix = np.diag(eigenvalues)
    invers_of_eigenvectors = np.linalg.inv(eigenvectors)
    return np.matmul(np.matmul(eigenvectors, np.linalg.matrix_power(digonal_matrix, n)), invers_of_eigenvectors)
    #return np.dot(np.dot(eigenvectors, np.linalg.matrix_power(digonal_matrix, n)), invers_of_eigenvectors)

print(fibo_eig(A, 5))
print(fibo_recursive(A, 5))

[[8. 5.]
 [5. 3.]]
[[8 5]
 [5 3]]


Q2-C mohasebe zaman

In [3]:
time = 1000
first = np.testing.measure('fibo_recursive(A, 1234)', time)
second = np.testing.measure('fibo_eig(A, 1234)', time)

print(first, " s")
print(second, " s")

0.01  s
0.03  s


Q1-A

In [4]:
import numpy as np
import math

def magnitude(vector):
    sum = 0
    for i in range(len(vector)):
        sum += vector[i] * vector[i]
    return math.sqrt(sum)
def dominant_eigenvector(matrix, iteration):
    guess = np.ones(matrix.shape[1])
    for i in range(iteration):
        last = np.dot(guess, matrix)
        normalize = np.linalg.norm(last)
        for j in range(len(last)):
            last[j] = last[j] / normalize
        if(magnitude(last - guess) < 0.001):
            return last
        guess = last
    return guess
matrix = np.array([
    [0, 0.8, 0.6, 0.1, 0, 0],
    [0.8, 0, 0.9, 0, 0, 0],
    [0.6, 0.9, 0, 0, 0.3, 0.2],
    [0.1, 0, 0, 0, 0.6, 0.7],
    [0, 0, 0.3, 0.6, 0, 0.8],
    [0, 0, 0.2, 0.7, 0.8, 0]
])
x = dominant_eigenvector(matrix, 1000)
print(x)
scores = list(enumerate(x, start = 1))
sortedSocres = sorted(scores, key = lambda t : t[1])
print(sortedSocres[len(sortedSocres) - 1] ," ", sortedSocres[len(sortedSocres) - 2], " ", sortedSocres[len(sortedSocres) - 3])

[0.41597176 0.46426306 0.50270124 0.30499445 0.36842513 0.36049977]
(3, np.float64(0.5027012365868218))   (2, np.float64(0.4642630604442141))   (1, np.float64(0.41597176100953864))


Q1-B

In [5]:
import numpy as np

sum1 = np.sum(np.dot(matrix, x))
sum2 = np.dot(x, x)
landa = sum1 / sum2
B = matrix - landa * np.dot(x, x.T)
diagonal_matrix = np.zeros((len(B), len(B)))
for i in range(len(B)):
    sum = 0
    for j in range(len(B)):
        sum += B[i][j]
    diagonal_matrix[i][i] = sum
laplas = diagonal_matrix - B
print(laplas)
def inverse_Power_Iteration(mat):
    temp = np.ones(mat.shape[1])
    identity = np.zeros((len(mat), len(mat)))
    for i in range(len(mat)):
        identity[i][i] = 1
    zarib = mat - 0.001 * identity
    for i in range(50):
        temp1 = np.linalg.solve(zarib, temp)
        temp1 = temp1 / np.linalg.norm(temp1)
        temp = temp1
    eigenvalue = np.dot(temp.T, np.dot(mat, temp)) / np.dot(temp.T, temp)
    return eigenvalue + 0.001, temp  
eigenvalue, eigenvector = inverse_Power_Iteration(laplas)
print(eigenvalue, " " , eigenvector)
if(eigenvalue > 0):
    print("graph is fully connected.")


[[-18.92385934   3.28477187   3.48477187   3.98477187   4.08477187
    4.08477187]
 [  3.28477187 -18.72385934   3.18477187   4.08477187   4.08477187
    4.08477187]
 [  3.48477187   3.18477187 -18.42385934   4.08477187   3.78477187
    3.88477187]
 [  3.98477187   4.08477187   4.08477187 -19.02385934   3.48477187
    3.38477187]
 [  4.08477187   4.08477187   3.78477187   3.48477187 -18.72385934
    3.28477187]
 [  4.08477187   4.08477187   3.88477187   3.38477187   3.28477187
  -18.72385934]]
0.001   [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]
graph is fully connected.


Q1-C

In [6]:
def nullSpace(matrix):
    eigenvalue, eigenvector = np.linalg.eigh(matrix)
    zero_v = np.isclose(eigenvalue, 0, atol = 0.0001)
    vectors = eigenvector[:, zero_v]
    if(vectors.shape[1] == 1):
        return True
    else:
        return False
print("is graph fully connected?", nullSpace(laplas))

is graph fully connected? True
